#!/usr/bin/env bash
#
# One-shot VPS deploy for PPC OS.
#
#   bash scripts/deploy-vps.sh ads.comfecto.com
#
# What it does:
#   1. Installs Docker if it is not already present (Ubuntu/Debian)
#   2. Generates fresh secrets — nothing is reused from a laptop .env
#   3. Writes .env, leaving the Amazon credentials for you to paste in
#   4. Starts the stack behind Caddy with automatic HTTPS
#   5. Runs migrations and seeds the first admin user
#
# It is safe to re-run: an existing .env is never overwritten, because doing so
# would rotate FERNET_KEY and silently invalidate the stored Amazon token.
set -euo pipefail

DOMAIN="${1:-}"
if [[ -z "$DOMAIN" ]]; then
    echo "Usage: bash scripts/deploy-vps.sh <domain>" >&2
    echo "Example: bash scripts/deploy-vps.sh ads.comfecto.com" >&2
    exit 1
fi

say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m !  %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m !! %s\033[0m\n' "$*" >&2; exit 1; }

[[ -f docker-compose.yml ]] || die "Run this from the ppc-os directory."

# ── 1. Docker ──────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
    say "Installing Docker"
    curl -fsSL https://get.docker.com | sh
else
    say "Docker already installed ($(docker --version))"
fi

docker compose version >/dev/null 2>&1 \
    || die "The Docker Compose plugin is missing. Install docker-compose-plugin and re-run."

# ── 2. Ports ───────────────────────────────────────────────────────────────
# Checked before anything is built: a port conflict discovered after a ten
# minute image build is a waste, and Caddy cannot get a certificate without 80.
say "Checking ports 80 and 443 are free"
for port in 80 443; do
    if ss -lntp 2>/dev/null | grep -q ":${port} "; then
        ss -lntp | grep ":${port} " || true
        die "Port ${port} is already in use. Stop whatever holds it, then re-run."
    fi
done
echo "  both free"

# ── 3. Secrets ─────────────────────────────────────────────────────────────
if [[ -f .env ]]; then
    say ".env already exists — keeping it"
    warn "Not regenerating secrets. Rotating FERNET_KEY would invalidate the"
    warn "stored Amazon refresh token and force OAuth to be run again."
else
    say "Generating fresh secrets"
    POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
    JWT_SECRET_KEY="$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)"
    SEED_ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 20)"
    FERNET_KEY="$(docker run --rm python:3.12-slim sh -c \
        'pip install --quiet cryptography && python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"')"

    cat > .env <<ENVEOF
# Generated by scripts/deploy-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Every secret here is new. Nothing was copied from a development machine.

POSTGRES_USER=ppc_os
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=ppc_os

JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=480

# Encrypts the stored Amazon refresh token. Changing this invalidates that
# token and forces the Amazon account to be reconnected.
FERNET_KEY=${FERNET_KEY}

# ── Amazon Ads — PASTE THESE IN BEFORE STARTING ────────────────────────────
AMAZON_CLIENT_ID=PASTE_ME
AMAZON_CLIENT_SECRET=PASTE_ME
AMAZON_MOCK_MODE=false
# Must match EXACTLY what is registered in your Amazon LWA application.
AMAZON_REDIRECT_URI=https://${DOMAIN}/accounts/oauth/callback
AMAZON_API_BASE_URL=https://advertising-api.amazon.com

# ── Safety ─────────────────────────────────────────────────────────────────
# OFF. The app can read and suggest, but cannot change the ad account.
# Turn on only when someone has decided to start applying changes.
AMAZON_WRITE_ENABLED=false

# ── First admin. Change the password after first sign-in. ──────────────────
SEED_ADMIN_EMAIL=admin@comfecto.com
SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
SEED_USER_EMAIL=user@comfecto.com
SEED_USER_PASSWORD=${SEED_ADMIN_PASSWORD}

# ── Optional: where failure alerts go. Free, and worth doing. ──────────────
ALERT_WEBHOOK_URL=

FRONTEND_URL=https://${DOMAIN}
ENV=production
ENVEOF
    chmod 600 .env
    say "Secrets written to .env (mode 600)"
    echo
    echo "  Admin login will be:  admin@comfecto.com"
    echo "  Admin password:       ${SEED_ADMIN_PASSWORD}"
    echo
    warn "Write that password down now. It is in .env, but not shown again."
fi

# ── 4. Amazon credentials ──────────────────────────────────────────────────
if grep -q "PASTE_ME" .env; then
    echo
    warn "AMAZON_CLIENT_ID / AMAZON_CLIENT_SECRET are still placeholders."
    warn "Edit .env, paste them in, then re-run this script."
    echo
    echo "  nano .env"
    echo
    exit 1
fi

# ── 5. Caddy domain ────────────────────────────────────────────────────────
if [[ -f Caddyfile ]] && ! grep -q "^${DOMAIN} {" Caddyfile; then
    say "Pointing Caddyfile at ${DOMAIN}"
    sed -i.bak -E "s/^[a-z0-9.-]+ \{/${DOMAIN} {/" Caddyfile
fi

# ── 6. DNS ─────────────────────────────────────────────────────────────────
say "Checking ${DOMAIN} resolves here"
RESOLVED="$(getent hosts "$DOMAIN" | awk '{print $1}' | head -1 || true)"
PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org || echo '')"
if [[ -n "$RESOLVED" && -n "$PUBLIC_IP" && "$RESOLVED" != "$PUBLIC_IP" ]]; then
    warn "${DOMAIN} resolves to ${RESOLVED}, but this server is ${PUBLIC_IP}."
    warn "Let's Encrypt will fail until DNS points here. Continuing anyway —"
    warn "Caddy retries automatically once DNS catches up."
elif [[ -n "$RESOLVED" ]]; then
    echo "  ${DOMAIN} -> ${RESOLVED}  (matches this server)"
fi

# ── 7. Build and start ─────────────────────────────────────────────────────
# The dev override is excluded deliberately: it swaps the production build for
# `npm run dev` and mounts source over the container.
COMPOSE="docker compose -f docker-compose.yml -f docker-compose.prod.yml"

say "Building images (this takes a few minutes the first time)"
$COMPOSE build

say "Starting the stack"
$COMPOSE up -d

say "Waiting for Postgres"
for _ in $(seq 1 60); do
    if $COMPOSE exec -T postgres pg_isready -U ppc_os >/dev/null 2>&1; then
        echo "  ready"; break
    fi
    sleep 2
done

say "Applying database migrations"
$COMPOSE exec -T api alembic upgrade head

say "Seeding the first users"
$COMPOSE exec -T api python -m app.modules.auth.seed || true

# ── 8. Verify ──────────────────────────────────────────────────────────────
say "Checking the app answers"
sleep 5
$COMPOSE exec -T api curl -fsS http://localhost:8000/health >/dev/null \
    && echo "  API healthy" || warn "API did not answer — check: $COMPOSE logs api"

say "Reclaiming build cache"
docker builder prune -af >/dev/null 2>&1 || true

cat <<DONE

────────────────────────────────────────────────────────────────────────
 Deployed.

   https://${DOMAIN}

 The certificate can take a minute on first start. If the browser warns
 about HTTPS, wait 60 seconds and reload.

 Writes to Amazon are OFF. The app can read, analyse and suggest; it
 cannot change the ad account until someone turns that on deliberately.

 Next:
   1. Sign in, go to Settings -> Accounts, and connect the Amazon account
      (OAuth must be re-run here — this server has its own FERNET_KEY).
   2. Register this redirect URI in your Amazon LWA app, exactly:
        https://${DOMAIN}/accounts/oauth/callback
   3. Run a first sync. It takes 20-40 minutes per report.
   4. Set ALERT_WEBHOOK_URL in .env so failures reach someone.

 Useful:
   $COMPOSE logs -f api
   $COMPOSE ps
   bash scripts/backup-db.sh
────────────────────────────────────────────────────────────────────────
DONE
